export enum EntityType {
    POKEMON = 'pokemon',
    POKEMON_SPECIES = 'pokemon-species',
    POKEMON_COLOR = 'pokemon-color',
    POKEMON_SHAPE = 'pokemon-shape',
    POKEMON_TYPE = 'type',
    POKEMON_ABILITY = 'ability',
    POKEMON_EGG_GROUP = 'egg-group',
    POKEMON_GENDER = 'gender',
    POKEMON_GROWTH_RATE = 'growth-rate',
    POKEMON_NATURE = 'nature',
    POKEMON_FORM = 'pokemon-form',
    POKEMON_HABITAT = 'pokemon-habitat',
    POKEMON_STATS = 'stat',
    MOVE = 'move',
    MOVE_CATEGORY = 'move-category',
    LANGUAGE = 'language',
    GENERATION = 'generation',
    POKEDEX = 'pokedex',
    VERSION = 'version',
    VERSION_GROUP = 'version-group',
    LOCATION = 'location',
    LOCATION_AREA = 'location-area',
    REGION = 'region',
}
